@extends('layouts.app')

@section('content')
    @include('home.sections.search_bar')
    @include('home.sections.hero')
    @include('home.sections.values')
    @include('home.sections.comfort')
    @include('home.sections.schedule')
    @include('home.sections.practitioner_chats')
    @include('home.sections.gifts')
    @include('home.sections.mindful_times_ribbon')
    @include('home.sections.mindful_times_more')
    @include('home.sections.reset_guide')
    @include('home.sections.newsletter_or_card')
    @include('home.sections.partners')
@endsection
